apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: {{ .Values.replicaCount }}
  # selector tells us any pod with same name under matchLabels belongs to the above Deployment
  selector:
    # pods within k8s have different names but we can give them the same label 
    # so we know which ones are replicas of the same service
    matchLabels:
      app: mongo
  template: # configs the pods of k8s
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        ports:
        - containerPort: {{ .Values.mongo.service.port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME # required name by mongodb
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD # required name by mongodb
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
