replicaCount: 2

image:
  repository: nanajanashia/k8s-demo-app:v1.0
  tag: v1.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30100

mongo:
  image:
    repository: mongo
    tag: 5.0
  service:
    port: 27017
    targetPort: 27017